# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.14.4
_src_path: gl:openscm/copier-core-python-repository
conda_release: false
email: zebedee.nicholls@climate-resource.com
include_cli: false
name: Zebedee Nicholls
notebook_based_docs: true
package_manager: uv
pandas_doctests: false
plot_dependencies: false
project_description_short: Software developer kit for interacting with the WCRP-CMIP
    variable registry
project_name_human: WCRP-CMIP Variable Registry SDK
project_name_pip: wcrp-cmip-variable-registry-sdk
project_name_python: wcrp_cmip_variable_registry_sdk
project_url: https://github.com/WCRP-CMIP/Variable-Registry
track_lock_file: true
