site_name: Variable Registry Documentation
site_url: https://WCRP-CMIP.github.io/Variable-Registry/
repo_url: https://github.com/WCRP-CMIP/Variable-Registry

docs_dir: ../../docs
site_dir: ./site

theme:
  name: material
  logo: assets/CMIP_Icon_CMYK_negative.svg
  custom_dir: overrides
  features:
    - navigation.footer
    - search.suggest
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.instant.progress
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  copyright: CCBY04 2023+ Daniel Ellis for the CMIP-IPO
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: lime
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: lime
      accent: lime
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search
  - plotly:
      js_url: https://cdn.plot.ly/plotly-latest.min.js
      json_path: ./assets
      global_plotlyjs: true
      auto_load: true
      offline: true
  - gen-files:
      scripts:
        - hooks/copy_static_assets.py  # Copy JavaScript and CSS files
        - hooks/process_src_data_robust.py  # Robust path checking version
        - hooks/process_json_summaries.py  # Process JSON files for data summaries

        - hooks/generate_repo_stats.py  # Generate simple repository statistics

  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: true
      tab_length: 2



hooks:
  - hooks/nav_post_gen_v2.py  # Updated to detect virtual files
  - hooks/readme_injector.py  # Inject README.md content into index.md

extra:
  version:
    provider: mike
    
extra_css: 
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
  - https://cdn.plot.ly/plotly-latest.min.js
  - scripts/embed.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
        base_path: ['docs']
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 

# Navigation will be auto-generated or use mipcvs-wiki defaults
# Generated pages from JSON will be added to docs/generated/

# Ensure assets directory is available for graphs
assets_dir: assets
