name: New Issue Processing

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: write
  id-token: write
  pull-requests: write

jobs:
  new-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Run the parser on a new issue
        id: new-issue-action
        uses: WCRP-CMIP/CMIP-LD/actions/new-issue@main
