name: Process New Issues

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: write
  id-token: write
  pull-requests: write

jobs:
  new-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Process new issue
        uses: WCRP-CMIP/CMIP-LD/actions/new-issue@main
