name: Process New Issues

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'edited'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse issue content
        run: |
          echo "## Issue Processing" >> $GITHUB_STEP_SUMMARY
          echo "Processing issue #${{ github.event.issue.number }}" >> $GITHUB_STEP_SUMMARY
          echo "Title: ${{ github.event.issue.title }}" >> $GITHUB_STEP_SUMMARY
          echo "Author: ${{ github.event.issue.user.login }}" >> $GITHUB_STEP_SUMMARY
          
          # Extract issue content
          echo "${{ github.event.issue.body }}" > issue-content.txt
          
          # Basic parsing - look for JSON-LD patterns
          if grep -q "\"@context\"" issue-content.txt; then
            echo "Found JSON-LD content in issue" >> $GITHUB_STEP_SUMMARY
            echo "issue-contains-jsonld=true" >> $GITHUB_OUTPUT
          fi
          
          # Look for data request patterns  
          if grep -qi "request\|add\|new.*variable" issue-content.txt; then
            echo "Detected data request" >> $GITHUB_STEP_SUMMARY
            echo "issue-type=data-request" >> $GITHUB_OUTPUT
          fi
        id: parse

      - name: Add appropriate labels
        if: steps.parse.outputs.issue-contains-jsonld == 'true'
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label "jsonld,needs-review"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on issue
        if: steps.parse.outputs.issue-type == 'data-request'
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "
          Thank you for your data request! 🎯
          
          This issue has been automatically processed and labeled for review.
          A team member will review your request and provide feedback soon.
          
          Please ensure your request includes:
          - Clear description of the data needed
          - Use case or scientific justification  
          - Any specific format requirements
          
          ---
          *This is an automated response*"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
